services:
  server:
    container_name: server
    env_file:
      - .env.development
    environment:
      - DATABASE_HOST=host.docker.internal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
#    volumes:
#      - ./:/app
#      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend

networks:
  backend:
    driver: bridge

