services:
  server:
    container_name: server
    env_file:
      - .env.development
    environment:
      - DATABASE_HOST=host.docker.internal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend

  db:
    depends_on:
      - server
    image: postgres
    restart: always
    env_file:
      - .env.development
    environment:
      POSTGRES_DB: $DATABASE_DBNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

networks:
  backend:
    driver: bridge

volumes:
  database_data:
    driver: local
