version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      DATABASE_DBNAME: $DATABASE_DBNAME
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_USER: $DATABASE_USER
      DATABASE_PORT: $DATABASE_PORT
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - $DATABASE_PORT:$DATABASE_PORT

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database_data:
    driver: local
