name: Fancy Deployment

on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build docker_compose
        run: docker-compose up -d --build
      - name: Build application
        run: docker-compose exec -T service yarn build
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy application
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME : ${{ secrets.SSH_HOST }}
          USERNAME : ${{ secrets.SSH_USER }}
          DATABASE_DBNAME : ${{ secrets.DATABASE_DBNAME }}
          DATABASE_HOST : ${{ secrets.DATABASE_HOST }}
          DATABASE_PASSWORD : ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT : ${{ secrets.DATABASE_PORT }}
          DATABASE_USER : ${{ secrets.DATABASE_USER }}
        run: |
          touch .env
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '

          cd /UplinesBackend &&
          git checkout develop &&
          git fetch --all &&
          git reset --hard origin/develop &&
          git pull origin develop &&
          docker-compose up -d --build
